# Generated by Django 3.1.7 on 2021-02-22 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0002_auto_20210222_1544'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
