# Generated by Django 3.1.7 on 2021-02-22 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0003_auto_20210222_1549'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='company_name',
            field=models.CharField(default=None, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='first_name',
            field=models.CharField(default=None, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_name',
            field=models.CharField(default=None, max_length=20, null=True),
        ),
    ]
