# Generated by Django 3.1.7 on 2021-03-09 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0006_auto_20210222_1600'),
    ]

    operations = [
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('institute_name', models.CharField(default=None, max_length=20, null=True)),
                ('institute_location', models.CharField(default=None, max_length=20, null=True)),
                ('degree', models.CharField(default=None, max_length=20, null=True)),
                ('field_of_study', models.CharField(default=None, max_length=20, null=True)),
                ('graduation_start_date', models.DateField(default=None, null=True)),
                ('graduation_end_date', models.DateField(auto_now=True, null=True)),
                ('still_working', models.BooleanField(null=True)),
                ('description', models.TextField(default=None, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Personal_info',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(default=None, max_length=20, null=True)),
                ('last_name', models.CharField(default=None, max_length=20, null=True)),
                ('profession', models.CharField(default=None, max_length=20, null=True)),
                ('address', models.CharField(default=None, max_length=20, null=True)),
                ('phone', models.CharField(default=None, max_length=20, null=True)),
                ('email', models.EmailField(default=None, max_length=20, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='upload/profile_pic')),
            ],
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skill', models.CharField(default=None, max_length=20, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Summary',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('backgound_description', models.TextField(default=None, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Work_history',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_title', models.CharField(default=None, max_length=20, null=True)),
                ('employer', models.CharField(default=None, max_length=20, null=True)),
                ('work_description', models.TextField(default=None, max_length=255, null=True)),
                ('start_date', models.DateField(default=None, null=True)),
                ('end_date', models.DateField(auto_now=True, null=True)),
                ('no_experience', models.BooleanField(null=True)),
                ('still_working', models.BooleanField(null=True)),
            ],
        ),
    ]
