# Generated by Django 3.1.7 on 2021-03-09 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0007_education_personal_info_skill_summary_work_history'),
    ]

    operations = [
        migrations.AlterField(
            model_name='education',
            name='graduation_end_date',
            field=models.DateField(default=None, null=True),
        ),
    ]
