# Generated by Django 3.1.7 on 2021-03-09 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0008_auto_20210309_1837'),
    ]

    operations = [
        migrations.AlterField(
            model_name='work_history',
            name='end_date',
            field=models.DateField(default=None, null=True),
        ),
    ]
