# Generated by Django 3.1.7 on 2021-03-11 06:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0009_auto_20210309_1839'),
    ]

    operations = [
        migrations.RenameField(
            model_name='education',
            old_name='still_working',
            new_name='still_studing',
        ),
    ]
