# Generated by Django 3.1.7 on 2021-03-14 09:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0010_auto_20210311_1202'),
    ]

    operations = [
        migrations.AddField(
            model_name='personal_info',
            name='user_id',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='resume.user'),
        ),
    ]
