# Generated by Django 3.1.7 on 2021-03-14 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0011_personal_info_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personal_info',
            name='user_id',
            field=models.IntegerField(default=None, max_length=10, null=True),
        ),
    ]
