# Generated by Django 3.1.6 on 2021-03-15 10:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0011_personal_info_user_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='education',
            old_name='still_studing',
            new_name='still_studying',
        ),
        migrations.RenameField(
            model_name='summary',
            old_name='backgound_description',
            new_name='background_description',
        ),
    ]
