# Generated by Django 3.1.7 on 2021-03-24 08:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0014_work_history_personal_info_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='education',
            name='personal_info_id',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='resume.personal_info'),
        ),
        migrations.AddField(
            model_name='skill',
            name='personal_info_id',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='resume.personal_info'),
        ),
        migrations.AddField(
            model_name='summary',
            name='personal_info_id',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='resume.personal_info'),
        ),
    ]
