# Generated by Django 3.1.7 on 2021-03-24 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0015_auto_20210324_1452'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personal_info',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='upload/profile_pic/'),
        ),
    ]
