# Generated by Django 3.1.7 on 2021-03-24 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0016_auto_20210324_1635'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personal_info',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='upload/profile_pic'),
        ),
    ]
