# Generated by Django 3.1.7 on 2021-03-24 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0019_auto_20210324_1715'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personal_info',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='upload/profile_pic'),
        ),
    ]
