# Generated by Django 3.1.7 on 2021-03-24 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0021_auto_20210324_1730'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personal_info',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='upload/image/'),
        ),
    ]
