# Generated by Django 3.1.7 on 2021-03-24 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0022_auto_20210324_1738'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personal_info',
            name='image',
            field=models.ImageField(default=None, null=True, upload_to='upload/image/'),
        ),
    ]
