# Generated by Django 3.1.6 on 2021-05-01 15:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0024_post'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='content',
            new_name='job_details',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='title',
            new_name='job_title',
        ),
    ]
