# Generated by Django 3.1.6 on 2021-05-01 15:56

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0025_auto_20210501_2126'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='job_details',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
