# Generated by Django 3.1.6 on 2021-05-02 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0026_auto_20210501_2156'),
    ]

    operations = [
        migrations.CreateModel(
            name='Applicant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(default=None, max_length=20, null=True)),
                ('last_name', models.CharField(default=None, max_length=20, null=True)),
                ('profession', models.CharField(default=None, max_length=20, null=True)),
                ('address', models.CharField(default=None, max_length=20, null=True)),
                ('phone', models.CharField(default=None, max_length=20, null=True)),
                ('email', models.EmailField(default=None, max_length=20, null=True)),
                ('resume', models.FileField(default=None, null=True, upload_to='upload/file/')),
            ],
        ),
    ]
